import { GameState, ResourceType, ScalingDef, UpgradeDef } from './types';
import { formatNumber } from './utils';

export const UPGRADES: UpgradeDef[] = [
  {
    id: 'shark_strength',
    name: 'Shark Strength',
    description: (lvl) => `Increases Fish eaten by +1 per level.`,
    effectDescription: (lvl) => `Effect: +${formatNumber(lvl * 1)}`,
    baseCost: 10,
    costMultiplier: 1.5,
    currency: ResourceType.FISH,
    basePower: 1,
  },
  {
    id: 'shark_agility',
    name: 'Shark Agility',
    description: (lvl) => `Increases base Shark Level bonus by +1 per level.`,
    effectDescription: (lvl) => `Effect: +${formatNumber(lvl * 5)}`,
    baseCost: 100,
    costMultiplier: 2.2,
    currency: ResourceType.FISH,
    basePower: 5,
  },
  {
    id: 'hunting_tactics',
    name: 'Hunting Tactics',
    description: (lvl) => `Increases base fish income by +10 per level.`,
    effectDescription: (lvl) => `Effect: +${formatNumber(lvl * 10)}/s`,
    baseCost: 500,
    costMultiplier: 1.8,
    currency: ResourceType.FISH,
    basePower: 10,
  },
  {
    id: 'shark_teeth',
    name: 'Shark Teeth',
    description: (lvl) => `Boosts 1st Upgrade exponent by +50%.`,
    effectDescription: (lvl) => `Effect: ^${(1 + lvl * 0.1).toFixed(2)}`,
    baseCost: 5000,
    costMultiplier: 3.5,
    currency: ResourceType.FISH,
    basePower: 0.1,
    isExponential: true,
  },
  {
    id: 'ocean_currents',
    name: 'Ocean Currents',
    description: (lvl) => `Passive fish generation +20 per level.`,
    effectDescription: (lvl) => `Effect: +${formatNumber(lvl * 20)}/s`,
    baseCost: 25000,
    costMultiplier: 2.5,
    currency: ResourceType.FISH,
    basePower: 20,
  },
  {
    id: 'shark_exponent',
    name: 'Shark Exponent',
    description: (lvl) => `Increases Fish exponent by +1%.`,
    effectDescription: (lvl) => `Effect: ^${(1 + lvl * 0.01).toFixed(2)}`,
    baseCost: 100000,
    costMultiplier: 10,
    currency: ResourceType.FISH,
    basePower: 0.01,
    isExponential: true,
  },
  {
    id: 'razor_fins',
    name: 'Razor Fins',
    description: (lvl) => `Slices through water, +50 fish/click base.`,
    effectDescription: (lvl) => `Effect: +${formatNumber(lvl * 50)} click`,
    baseCost: 250000,
    costMultiplier: 4,
    currency: ResourceType.FISH,
    basePower: 50,
  },
  {
    id: 'radioactive_shark',
    name: 'Radioactive Shark',
    description: (lvl) => `Double radiation production per level.`,
    effectDescription: (lvl) => `Effect: x${formatNumber(Math.pow(2, lvl))}`,
    baseCost: 1e6,
    costMultiplier: 100,
    currency: ResourceType.FISH,
    basePower: 2,
    isExponential: true,
  },
  {
    id: 'top_predator',
    name: 'Top Predator',
    description: (lvl) => `Dominates the ocean. Income x1.5 per level.`,
    effectDescription: (lvl) => `Effect: x${formatNumber(Math.pow(1.5, lvl))}`,
    baseCost: 5e7,
    costMultiplier: 15,
    currency: ResourceType.FISH,
    basePower: 1.5,
    isExponential: true,
  },
  {
    id: 'super_shark',
    name: 'Super Shark',
    description: (lvl) => `Increases Fish eaten by x3 per level.`,
    effectDescription: (lvl) => `Effect: x${formatNumber(Math.pow(3, lvl))}`,
    baseCost: 1e9,
    costMultiplier: 50,
    currency: ResourceType.FISH,
    basePower: 3,
    isExponential: true,
  },
];

export const SCALINGS: ScalingDef[] = [
    {
        id: 'scale_lvl_5',
        name: 'Novice Evolution',
        requiredType: 'LEVEL',
        threshold: 5,
        bonusPercent: 50,
        isUnlocked: (gs) => gs.sharkLevel >= 5,
        targetResource: ResourceType.FISH
    },
    {
        id: 'scale_fish_1k',
        name: 'Fish Hoarder',
        requiredType: 'RESOURCE',
        requiredId: ResourceType.FISH,
        threshold: 1000,
        bonusPercent: 25,
        isUnlocked: (gs) => gs.lifetimeEarnings[ResourceType.FISH] >= 1000,
        targetResource: ResourceType.FISH
    },
    {
        id: 'scale_prestige_lvl_8',
        name: 'Prestige Awareness',
        requiredType: 'LEVEL',
        threshold: 8,
        bonusPercent: 100,
        isUnlocked: (gs) => gs.sharkLevel >= 8,
        targetResource: ResourceType.PRESTIGE
    },
    {
        id: 'scale_lvl_10',
        name: 'Shark Instinct',
        requiredType: 'LEVEL',
        threshold: 10,
        bonusPercent: 100,
        isUnlocked: (gs) => gs.sharkLevel >= 10,
        targetResource: ResourceType.FISH
    },
    {
        id: 'scale_fish_1m',
        name: 'Ocean Dominator',
        requiredType: 'RESOURCE',
        requiredId: ResourceType.FISH,
        threshold: 1000000,
        bonusPercent: 200,
        isUnlocked: (gs) => gs.lifetimeEarnings[ResourceType.FISH] >= 1000000,
        targetResource: ResourceType.FISH
    },
    {
        id: 'scale_lvl_25',
        name: 'Apex Predator',
        requiredType: 'LEVEL',
        threshold: 25,
        bonusPercent: 500,
        isUnlocked: (gs) => gs.sharkLevel >= 25,
        targetResource: ResourceType.FISH
    }
];